### ISSUE TITLE
Smooth Lines in the Chart

### ISSUE THREAD

**Issue by liuderchi** [liuderchi/light-react-redux-weather-map#1]
it would look better if the line in the chart is smooth.
Currently there are *cusps*.

![example](https://cloud.githubusercontent.com/assets/4994705/26413720/6ecc65f6-40df-11e7-81ca-72e25735275b.png)

**GOAL**
  - to have *better interpolation methods* to have curve with higher dimension (e.g. Bézier)

**NOTE**
  - currently it is drawn with svg `<polyline>` with point data specified in `points` attr
  - relevant react component: [`react-sparklines`](https://github.com/borisyankov/react-sparklines)

**TODO**

  - [x] survey possible curve interpolation api for `react-sparklines`
  - [x] understand how `react-sparklines` generate `polyline` with data
  - [x] check `polyline` attr to support Bézier curves
  - [x] svg `path` survey

**Comment by liuderchi** [comment]
## Actions

  - [x] survey possible curve interpolation api for `react-sparklines`
      - from [`README.md`][readme] looks like NO API for smooth curve
          - using `<SparklinesLine />`
          - in src it has `<SparklinesCurve />` using svg `path` and additional points are inserted
      - ~~**PlanB**: manually insert points to *look* smoother. (Require Bézier Math Lib)~~
  - [x] understand how `react-sparklines` generate `polyline` with data
     - array of numbers will be processed then sent to `data` of `<polyline>`
  - [x] check `polyline` attr to support Bézier curves
      - NO. `polyline` is for straight lines. Adding more points won't help when zoomed.
      - BTW svg [`path`][svgpath] supports Bézier curve
      - ~~**PlanC** use other component to generate svg `path` from data (D3?)~~
  - [x] svg `path` survey
      - command `C` is for cubic Bézier curve
      - command `Q` is for quadratic Bézier curve
      - currently `<SparklinesCurve />` uses `C`

[readme]: https://github.com/borisyankov/react-sparklines/blob/master/README.md "README.md"
[svgpath]: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths "svgpath"


## Result

by using `<SparklinesCurve />` with setting prop `divisor`, we now have smoother curve
  - `divisor` is used to [insert additional control points for Bézier curve](https://github.com/borisyankov/react-sparklines/blob/master/src/SparklinesCurve.js#L22-L36)
      - I set it to 0.33 because it means adding 2 control points at 1/3 and 2/3 of the distance
      - how it looks when *zoomed 300%*

![compare-divosor-0 3](https://cloud.githubusercontent.com/assets/4994705/26428910/a9e29692-4116-11e7-87de-4e868bdd6006.png)




.
